net:
  input_dim : 784 # 28x28
  output_dim : 10
  num_layers : 3
  hidden_units : 256
optimizer:
  _target_: torch.optim.Adam
  lr : 0.001
  weight_decay : 0.0
regularizer:
  dropout : 0.0
  batch_norm : false
name: mlp_${.net.num_layers}_${.net.hidden_units}